// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: chats.sql

package pokedex

import (
	"context"

	"github.com/google/uuid"
)

const insertChatEntry = `-- name: InsertChatEntry :exec
INSERT INTO chats
  (id, user_pokemon_id)
SELECT
  $1,
  up.id
FROM user_pokemons up
WHERE up.user_id = $2
  AND up.pokemon_id = $3
ON CONFLICT (user_pokemon_id) DO UPDATE SET updated_at = NOW()
`

type InsertChatEntryParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PokemonID int32
}

func (q *Queries) InsertChatEntry(ctx context.Context, arg InsertChatEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertChatEntry, arg.ID, arg.UserID, arg.PokemonID)
	return err
}
