// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pokedex

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserPokemonID uuid.UUID
}

type ChatHistory struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ChatID    uuid.UUID
	Sender    string
	Message   string
}

type Evolution struct {
	ID          int32
	ChainID     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PokemonID   int32
	EvolvesToID sql.NullInt32
}

type Pokemon struct {
	ID             int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Height         int32
	Weight         int32
	PictureUrl     string
	BaseExperience int32
	Types          []string
	Hp             int32
	Attack         int32
	Defense        int32
	SpecialAttack  int32
	SpecialDefense int32
	Speed          int32
}

type User struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	AuthID     string
	Username   string
	Email      string
	PictureUrl string
}

type UserPokemon struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PokemonID int32
}
